-- MySQL Script generated by MySQL Workbench
-- Sun 07 Aug 2016 04:25:36 PM PDT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema wish_list
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `wish_list` ;

-- -----------------------------------------------------
-- Schema wish_list
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `wish_list` DEFAULT CHARACTER SET utf8 ;
USE `wish_list` ;

-- -----------------------------------------------------
-- Table `wish_list`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wish_list`.`users` ;

CREATE TABLE IF NOT EXISTS `wish_list`.`users` (
  `user_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `first_name` VARCHAR(255) NOT NULL COMMENT '',
  `last_name` VARCHAR(255) NOT NULL COMMENT '',
  `birthday` DATETIME NOT NULL COMMENT '',
  `email` VARCHAR(255) NOT NULL COMMENT '',
  `pw_hash` VARCHAR(255) NOT NULL COMMENT '',
  `updated_at` DATETIME NOT NULL COMMENT '',
  `created_at` DATETIME NOT NULL COMMENT '',
  PRIMARY KEY (`user_id`)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `wish_list`.`items`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wish_list`.`items` ;

CREATE TABLE IF NOT EXISTS `wish_list`.`items` (
  `item_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `item_name` VARCHAR(255) NOT NULL COMMENT '',
  `created_at` DATETIME NOT NULL COMMENT '',
  `updated_at` DATETIME NOT NULL COMMENT '',
  `users_user_id` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`item_id`)  COMMENT '',
  INDEX `fk_items_users1_idx` (`users_user_id` ASC)  COMMENT '',
  CONSTRAINT `fk_items_users1`
    FOREIGN KEY (`users_user_id`)
    REFERENCES `wish_list`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `wish_list`.`wish_list`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wish_list`.`wish_list` ;

CREATE TABLE IF NOT EXISTS `wish_list`.`wish_list` (
  `users_user_id` INT(11) NOT NULL COMMENT '',
  `items_item_id` INT(11) NOT NULL COMMENT '',
  `created_at` DATETIME NOT NULL COMMENT '',
  INDEX `fk_favourites_users1_idx` (`users_user_id` ASC)  COMMENT '',
  INDEX `fk_favourites_items1_idx` (`items_item_id` ASC)  COMMENT '',
  CONSTRAINT `fk_favourites_items1`
    FOREIGN KEY (`items_item_id`)
    REFERENCES `wish_list`.`items` (`item_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_favourites_users1`
    FOREIGN KEY (`users_user_id`)
    REFERENCES `wish_list`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
